
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatgpt?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    org:
#      example:
#        feign: debug



