
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatgpt?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234

#logging:
#  level:
#    org:
#      example:
#        feign: debug

